name: docs

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm install
      - name: Build VuePress site
        run: npm run docs:build
      - name: create-CNAME
        run: touch docs/CNAME && echo "zzzyss.top" > docs/CNAME
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{secrets.USERNAME}}
            server: ${{ secrets.HOST }}
            password: ${{ secrets.PASSWORD }} 
            port: ${{ secrets.PORT }}
            local_path: 'docs/.vuepress/dist'
            remote_path: '/root/page'
            sftpArgs: '-o ConnectTimeout=5'
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}